site_name: Detran

theme:
  language: pt-BR
  logo: assets/logo.png
  favicon: images/favicon.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
      primary: teal
      accent: lime
 
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Início: index.md
  - Pré-rastreabilidade:
    - Planejamento:
      - Aplicativos: 1_planejamento/aplicativos.md
      - Ferramentas: 1_planejamento/ferramentas.md
      - Rich Picture: 1_planejamento/Rich_picture.md
      - Termo: 1_planejamento/termos.md
    - Elicitação e Priorização:
      - Entrevista: 2_elicitação/entrevista.md
      - Questionário: 2_elicitação/questionario.md
      - Análise de documentos: 2_elicitação/analise_de_documentos.md
      - First things first: 2_elicitação/FTF.md
      - In or Out: 2_elicitação/in_or_out.md
      - Moscow: 2_elicitação/moscow.md
      - Personas: 2_elicitação/personas.md
      - Storytelling: 2_elicitação/storytelling.md
      - Requisitos elicitados: 2_elicitação/requisitos_elicitados.md
    - Modelagem:
      - Casos de uso: 3_modelagem/casos_de_uso.md
      - Cenários: 3_modelagem/cenarios.md
      - Especificação suplementar: 3_modelagem/especificacao_suplementar.md
      - Léxicos: 3_modelagem/lexico.md
    - Modelagem ágil:
      - Not Functionals Requirements: 4_modelagem_agil/NFR.md
      - Histórias de Usuário: 4_modelagem_agil/historias_de_usuarios.md
      - Backlog do Produto: 4_modelagem_agil/backlog.md
  - Verificação & Validação:
    - Verificação:
      - Verificação DETRAN:
        - Verificação geral: Verificação e Validação/Verificacao/Geral.md
        - Planejamento:
          - Verificação Aplicativos: Verificação e Validação/Verificacao/Entrega_1/verificacao_aplicativos.md
          - Verificação Cronograma: Verificação e Validação/Verificacao/Entrega_1/verificacao_cronograma.md
          - Verificação Ferramentas: Verificação e Validação/Verificacao/Entrega_1/verificacao_ferramentas.md
          - Verificação Rich Picture: Verificação e Validação/Verificacao/Entrega_1/verificacao_RichPicture.md
        - Elicitação e Priorização:
          #- Verificaçao 100$: Verificação e Validação/Verificacao/Entrega_2/100.md
          - Verificação Moscow: Verificação e Validação/Verificacao/Entrega_2/moscow.md
          - Verificação first things first: Verificação e Validação/Verificacao/Entrega_2/first_things_first.md
          - Verificação in or out: Verificação e Validação/Verificacao/Entrega_2/in-or-out.md
          - Verificação entrevista: Verificação e Validação/Verificacao/Entrega_2/verificacao_entrevista.md
          - Verificação Storytelling: Verificação e Validação/Verificacao/Entrega_2/verificacao_Storytelling.md
        - Modelagem:
          - Verificação Casos de uso: Verificação e Validação/Verificacao/Entrega_3/verificacao_casos_de_uso.md
          - Verificação Cenários: Verificação e Validação/Verificacao/Entrega_3/verificacao_cenarios.md
          - Verificação Especificação suplementar: Verificação e Validação/Verificacao/Entrega_3/verificacao_especificacao_suplementar.md
          - Verificação Léxicos: Verificação e Validação/Verificacao/Entrega_3/verificacao_lexicos.md
          - Verificação Requisitos elicitados: Verificação e Validação/Verificacao/Entrega_3/Verificação_Requisitos ilicitados.md
        - Modelagem ágil:
          - Verificação Backlog do Produto: Verificação e Validação/Verificacao/Entrega_4/verificacao_backlog.md
          - Verificação Histórias de Usuário: Verificação e Validação/Verificacao/Entrega_4/verificacao_historias_de_usuario.md
          - Verificação Not Functionals Requirements: Verificação e Validação/Verificacao/Entrega_4/verificacao_NFR.md
        - Pós-rastreabilidade:
          - Verificação Backward: Verificação e Validação/Verificacao/Entrega_6/Backward.md
          - Verificação Forward: Verificação e Validação/Verificacao/Entrega_6/fowrard.md
          - Verificação matriz de rastreabilidade: Verificação e Validação/Verificacao/Entrega_6/matriz.md
      - Verificação GRUPO + 1:
        - Planejamento:
          - Verificação Aplicativos: Verificacao_grupo_8/Entrega_1/verificacao_aplicativos.md
          - Verificação Cronograma: Verificacao_grupo_8/Entrega_1/verificacao_cronograma.md
          - Verificação Ferramentas: Verificacao_grupo_8/Entrega_1/verificacao_ferramentas.md
          - Verificação Rich Picture: Verificacao_grupo_8/Entrega_1/verificacao_RichPicture.md
        - Elicitação e Priorização:
          - Verificaçao 100$: Verificacao_grupo_8/Entrega_2/100.md
          - Verificação Moscow: Verificacao_grupo_8/Entrega_2/Moscow.md
          - Verificação Brainstorming: Verificacao_grupo_8/Entrega_2/Verificação_Brasinstorming.md
          - Verificação introspecção: Verificacao_grupo_8/Entrega_2/verificacao_introspeccao.md
          - Verificação Perfil de usuário: Verificacao_grupo_8/Entrega_2/verificacao_perfil_do_usuario.md
          - Verificação Questionário: Verificacao_grupo_8/Entrega_2/verificacao_questionario.md
        - Modelagem:
          - Verificação Casos de uso: Verificacao_grupo_8/Entrega_3/verificacao_casos_de_uso.md
          - Verificação Cenários: Verificacao_grupo_8/Entrega_3/verificacao_cenarios.md
          - Verificação Especificação suplementar: Verificacao_grupo_8/Entrega_3/verificacao_especificacao_suplementar.md
          - Verificação Léxicos: Verificacao_grupo_8/Entrega_3/verificacao_lexicos.md
        - Modelagem ágil:
          - Verificação Backlog do Produto: Verificacao_grupo_8/Entrega_4/backlog.md
          - Verificação Histórias de Usuário: Verificacao_grupo_8/Entrega_4/historia_de_usuario.md
          - Verificação Not Functionals Requirements: Verificacao_grupo_8/Entrega_4/NFR.md
    - Validação:
      - Métodos de pagamento: Verificação e Validação/Validação/metodos_pagamento.md
      - Anexar laudos: Verificação e Validação/Validação/anexo.md
      - Realizar cursos: Verificação e Validação/Validação/realizar-cursos.md
      - Transferência de pontuação: Verificação e Validação/Validação/Transferencia.md
  - Pós-rastreabilidade:
      - Backward From: pos_rastreabilidade/backward_from.md
      - Forward From: pos_rastreabilidade/foward-from.md
      - Matriz de Rastreabilidade: pos_rastreabilidade/matriz_de_rastreabilidade.md
  - Apresentações & Atas:
    - Apresentações: apresentações.md
    - Atas:
      - Ata 1: Atas/ata1.md
      - Ata 2: Atas/ata2.md
      - Ata 3: Atas/ata3.md
      - Ata 4: Atas/ata4.md
      - Ata 5: Atas/ata5.md
      - Modelo: Atas/modelo_atas.md
  - Cronograma: cronograma/cronograma_de_atividades.md
  - Conclusão:
    - Artefato Final: apresentacao_final/apresentacao_final.md
